import type { Model, View, ViewColumn } from '../model.ts';
import { refName } from '../refs.ts';

/** Map a column type (SQL primitive or scalars.yaml type) to a Postgres type. */
function sqlType(type: string, model: Model): string {
  const primitive: Record<string, string> = {
    uuid: 'UUID', text: 'TEXT', integer: 'INTEGER', bigint: 'BIGINT',
    boolean: 'BOOLEAN', timestamptz: 'TIMESTAMPTZ', jsonb: 'JSONB', numeric: 'NUMERIC',
  };
  if (primitive[type]) return primitive[type];
  const scalar = model.defs['scalars.yaml'][type] as Record<string, unknown> | undefined;
  if (scalar) {
    if (Array.isArray(scalar.enum)) return 'TEXT'; // enum stored as text (one name = one value)
    if (scalar.format === 'uuid') return 'UUID';
    if (scalar.type === 'integer') return type === 'MoneyCents' ? 'BIGINT' : 'INTEGER';
  }
  return 'TEXT';
}

function fedByNames(view: View): string[] {
  return view.fedBy.map((r) => refName(r.$ref)).filter((n): n is string => n !== null);
}

function constraints(col: ViewColumn): string {
  const parts: string[] = [];
  if (col.pk) parts.push('PK');
  if (col.unique) parts.push('unique');
  if (col.index) parts.push('index');
  if (col.nullable) parts.push('nullable');
  return parts.join(', ') || '—';
}

function mdTable(header: string[], rows: string[][]): string {
  const line = (cells: string[]) => `| ${cells.join(' | ')} |`;
  return [line(header), line(header.map(() => '---')), ...rows.map(line)].join('\n');
}

function viewBlock(view: View, model: Model): string {
  const slice = view.slice === 'V1' ? '🔭 V1' : '🛶 V0';
  const internal = view.internal ? ' · 🔒 internal' : '';
  const origin = view.reference ? '📦 reference (static seed)' : `source aggregate \`${view.aggregate}\``;
  const lines = [`### \`${view.name}\` · ${slice}${internal} · ${origin}`, ''];
  if (view.internal) lines.push('- **Consumed by**: command handlers / auth resolution (no GraphQL query).');
  if (view.reference) lines.push('- **Reference data**: seeded at deploy time (not event-fed).');
  else lines.push(`- **Fed by**: ${fedByNames(view).map((n) => `\`${n}\``).join(', ')}`);
  if (view.filters.length) lines.push(`- **Filters**: ${view.filters.join(' ')}`);
  if (view.rules.length) lines.push(`- **Rules**: ${view.rules.join(' ')}`);
  if (view.note) lines.push(`- **Note**: ${view.note}`);
  if (view.indexes.length) lines.push(`- **Indexes**: ${view.indexes.map((ix) => `\`(${ix.join(', ')})\``).join(', ')}`);
  lines.push('');
  lines.push(
    mdTable(
      // Show the declared (domain) type here; the physical SQL type lives in views.generated.sql.
      ['Column', 'Type', 'SQL', 'Constraints', 'Notes'],
      view.columns.map((c) => [`\`${c.name}\``, `\`${c.type}\``, `\`${sqlType(c.type, model)}\``, constraints(c), c.note ?? '']),
    ),
  );
  return lines.join('\n');
}

/** The §2 read-model section body (injected into database.md between GENERATED markers). */
export function emitViewsMarkdown(model: Model): string {
  return model.views.map((v) => viewBlock(v, model)).join('\n\n');
}

/** CREATE TABLE + index DDL for every view. */
export function emitViewsSql(model: Model): string {
  const tables = model.views.map((view) => {
    const cols = view.columns.map((c) => {
      const bits = [`  ${c.name}`, sqlType(c.type, model)];
      if (c.pk) bits.push('PRIMARY KEY');
      else if (c.unique) bits.push(c.nullable ? 'UNIQUE' : 'NOT NULL UNIQUE');
      else if (!c.nullable) bits.push('NOT NULL');
      return bits.join(' ');
    });
    const ddl = [`CREATE TABLE ${view.name} (`, cols.join(',\n'), ');'];
    const idx: string[] = [];
    const seen = new Set<string>(); // dedupe identical index column-lists
    const addIndex = (columns: string[]) => {
      const key = columns.join(',');
      if (seen.has(key)) return;
      seen.add(key);
      idx.push(`CREATE INDEX ON ${view.name} (${columns.join(', ')});`);
    };
    for (const c of view.columns) {
      if (c.index && !c.pk) addIndex([c.name]);
    }
    for (const ix of view.indexes) addIndex(ix);
    return [ddl.join('\n'), ...idx].join('\n');
  });
  return `-- GENERATED by tools/codegen from specs/views.yaml — do not edit by hand.\n-- Read tables (View_*): denormalized, query-shaped, rebuildable from domain_events.\n\n${tables.join('\n\n')}\n`;
}
